# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  GetSimilar:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - name: HTTP Request Action
        id: simissues
        uses: fjogeleit/http-request-action@v1.11.0
        with:
          url: https://ghsimilarissues.azurewebsites.net/simissues
          method: GET
      - name: Show Response
        run: |
            echo ${{ steps.myRequest.outputs.response }}
